'use client'

import Card from '@/components/ui/Card'
import type { NorthStar } from '@/types'

export interface WeeklySnapshotProps {
  weekNumber: number
  dateRange: string
  northStar: NorthStar
  dosesThisWeek: number
  thresholdRange: { floor: number | null; sweetSpot: number | null; ceiling: number | null } | null
  avgSignal: number | null
  avgTexture: number | null
  avgInterference: number | null
  unit: 'mg' | 'µg'
}

const northStarLabels: Record<NorthStar, string> = {
  clarity: 'Clarity',
  connection: 'Connection',
  creativity: 'Creativity',
  calm: 'Calm',
  exploration: 'Exploration',
}

function formatDose(value: number | null, unit: 'mg' | 'µg'): string {
  if (value === null) {
    return '—'
  }

  const decimals = Number.isInteger(value) ? 0 : 2
  return `${value.toFixed(decimals)} ${unit}`
}

function formatAverage(value: number | null): string {
  if (value === null) {
    return '—'
  }

  return value.toFixed(1)
}

export function WeeklySnapshot({
  weekNumber,
  dateRange,
  northStar,
  dosesThisWeek,
  thresholdRange,
  avgSignal,
  avgTexture,
  avgInterference,
  unit,
}: WeeklySnapshotProps) {
  const zones = [
    { label: 'LOW', value: thresholdRange?.floor ?? null },
    { label: 'SWEET SPOT', value: thresholdRange?.sweetSpot ?? null },
    { label: 'HIGH', value: thresholdRange?.ceiling ?? null },
  ] as const

  return (
    <Card padding="lg" className="animate-[fadeIn_800ms_ease-out]">
      <p className="font-mono text-xs tracking-widest uppercase text-bone">
        Week {weekNumber} · {dateRange}
      </p>

      <div className="mt-4 rounded-button bg-elevated p-3">
        <p className="font-mono text-xs tracking-widest uppercase text-bone">North Star</p>
        <p className="mt-2 font-sans text-sm text-ivory">🧭 {northStarLabels[northStar]}</p>
      </div>

      <div className="mt-3 rounded-button bg-elevated p-3">
        <p className="font-mono text-xs tracking-widest uppercase text-bone">Activity</p>
        <p className="mt-2 font-sans text-sm text-ivory">{dosesThisWeek} doses this week</p>
      </div>

      <div className="mt-4">
        <p className="font-mono text-xs tracking-widest uppercase text-bone">Threshold Range</p>
        <div className="mt-3 grid grid-cols-3 gap-3">
          {zones.map((zone) => (
            <div key={zone.label} className="rounded-button bg-elevated p-3 text-center">
              <p className="font-mono text-xs tracking-widest uppercase text-bone">{zone.label}</p>
              <p className="mt-2 font-mono text-sm text-ivory">{formatDose(zone.value, unit)}</p>
            </div>
          ))}
        </div>
      </div>

      <div className="mt-4">
        <p className="font-mono text-xs tracking-widest uppercase text-bone">STI Averages</p>
        <div className="mt-3 grid grid-cols-3 gap-3">
          <div className="rounded-button bg-elevated p-3 text-center">
            <p className="font-mono text-xs tracking-widest uppercase text-bone">Signal</p>
            <p className="mt-2 font-mono text-sm text-status-clear">{formatAverage(avgSignal)}</p>
          </div>
          <div className="rounded-button bg-elevated p-3 text-center">
            <p className="font-mono text-xs tracking-widest uppercase text-bone">Texture</p>
            <p className="mt-2 font-mono text-sm text-ivory">{formatAverage(avgTexture)}</p>
          </div>
          <div className="rounded-button bg-elevated p-3 text-center">
            <p className="font-mono text-xs tracking-widest uppercase text-bone">Interference</p>
            <p className="mt-2 font-mono text-sm text-status-elevated">{formatAverage(avgInterference)}</p>
          </div>
        </div>
      </div>

      <div className="mt-5 border-t border-ember/20 pt-3">
        <p className="font-sans text-xs text-ash">Generated by Threshold Compass</p>
      </div>
    </Card>
  )
}

export default WeeklySnapshot
